### ISSUE TITLE
Irc sever protected password

### ISSUE THREAD

**Issue by HariSeldon0fe** [mjsalerno/UnoBot#19]
hello, the server i am trying to connect to is password protected how would i set the bot up with a server password?

to be more specific i am trying to connect to a ZNC, however i would like it if the uno ai didn't connect with the ZNC since it would work anymore

**Comment by mjsalerno** [comment]
If you are talking about a nickserv password, a server password, or a web irc password then yes I can change the source to let you configure those. I have never used this with an IRC bouncer so I am not sure if it would work.

**Comment by mjsalerno** [comment]
I have added 3 kinds of passwords that you can configure, let me know if any of them work. The config names are nickSrvPasswd, serverPasswd, or webIRCPasswd

**Comment by HariSeldon0fe** [comment]
works perfectly thank you :)
